service: alexa-air-quality-skill

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, self:custom.region}
  stage: ${opt:stage, self:custom.stage}
  profile: ${opt:profile}
  deploymentBucket: ${opt:deploymentBucket}
  environment:
    ENV: ${opt:stage, self:custom.stage}
    ALEXA_APPLICATION_ID: ${file(./env.yml):ALEXA_APPLICATION_ID}

custom:
  region: eu-west-1
  stage: dev

functions:
  quality:
    handler: handler.quality
    events:
      - alexaSkill
